version: "3"
services:
  portal:
    build:
      context: portal
    ports:
      - "8080:80"
    environment:
      DB_URL: mariadb
      DB_USER: root
      DB_PASSWORD: password
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./portal/sql:/docker-entrypoint-initdb.d:ro
      
  lms:
    build:
      context: lms
    ports:
      - "80:80"
    volumes:
      - ./lms/questions:/questions
    depends_on:
      - mariadb

  lms-mariadb:
    image: mariadb
    container_name: lms-mariadb
    volumes:
      - ./lms/database.sql:/docker-entrypoint-initdb.d/database.sql:ro
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=lms
#    restart: always
    ports:
      - "3306:3306"

  pacs:
    build: ./pacs
    ports:
      - "5000:5000"
    # for debug
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./pacs/app:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./pacs/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  wiki:
    build:
      context: wiki
    ports:
      - "21:21"
      - "8000:5000"
